### ISSUE TITLE
are these agreements now in use by Shuttleworth?  

### ISSUE THREAD

**Issue by tvol** [ShuttleworthFoundation/agreement_templates#1]
@jasonhudson these are great. Are they in active use by the foundation now? Or are they still templates/drafts?

**Comment by jasonhudson** [comment]
Hi @tvol. These are in active use, I sent off 4 project agreements for signatures yesterday ;) The only customization we make is to the project specifications page to add detail to the agreement. Other than that, and some silly formatting issues that creep in, the content remains the same.

**Comment by tvol** [comment]
@jasonhudson awesome thanks!
