### ISSUE TITLE
Cosmetic issues in fellowship agreement

### ISSUE THREAD

**Issue by tbm** [ShuttleworthFoundation/agreement_templates#5]
There are some cosmetic issues in the fellowship agreement:

* Section 5.1.4.1 is empty

* Section 10.3.2 refers to "the Free Software [Grant Giver] General Public Licence". [Grant Giver] doesn't make sense there.  It's the GNU General Public License.

* 15.3. Once a mediator is agreed [he/she] must attempt: [he/she] as a replacement doesn't make sense since it doesn't refer to the fellow. So just "he/she".

* First paragraph of "[Grant Giver] Invested Companies":

> The [Grant Giver] thus    becomes invested

There's too much whitespace between "thus becomes"

* This is really minor but "Personal Interaction" talks about a "bi-annual meeting" whereas 6.10 talks about "bi-annual conferences" and 8.1has "biannual" (no dash)

**Comment by AndrewRens** [comment]
Thank for flagging these issues with the fellowship agreement, the following changes have been made to resolve them.

1. In How We Work under [Grant Giver] Invested Companies deleted excess spaces after 'thus'. 

2.In 5.1.1 inserted 'which is' after 'Company' for clarity.

3.Amended 10.3.2 to correctly refer to the GNU General Public License.

4.In 15.2 inserted 'to by the parties then' after 'agreed' and before '[he/she]' to clarify.

5. In 6.10 replaced 'bi-annual' with "twice yearly". In 8.1 replaced 'biannual'with 'twice yearly'."
Biannual and Bi-annual are ambiguous so we chose twice yearly which is not ambiguous to replace either form.

6. Deleted 5.1.4.1 which seems to have been solely the product of an errant return.

**Comment by tbm** [comment]
Thanks for your fast response!
